package com.hand33h.tulostaulu;

import android.app.Activity;
import android.content.ClipData;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class BattleReportAnalyzerActivity extends Activity {
 private static final int PICK=6201; private static final String PREFS="wos_tulostaulu",HISTORY_KEY="battle_history_v3";
 private final TextRecognizer recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS); private TextView status,result; private final StringBuilder merged=new StringBuilder();
 @Override protected void onCreate(Bundle b){super.onCreate(b);ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(32,40,32,48);root.setBackgroundColor(Color.rgb(7,23,39));sc.addView(root);root.addView(t("⚔️ BATTLE REPORT ANALYZER 7.1",24,Color.WHITE));root.addView(t("Multi-image OCR • casualties • heroes/GEN • joiner/skill clues • validation • CSV export",13,Color.rgb(205,226,238)));Button pick=new Button(this);pick.setText("VALITSE RAPORTTIKUVAT");pick.setOnClickListener(v->choose());root.addView(pick);Button history=new Button(this);history.setText("BATTLE HISTORY + FORMATION SUMMARY");history.setOnClickListener(v->showHistory());root.addView(history);Button export=new Button(this);export.setText("EXPORT BATTLE DATA (CSV / EXCEL)");export.setOnClickListener(v->exportCsv());root.addView(export);Button clear=new Button(this);clear.setText("TYHJENNÄ BATTLE HISTORY");clear.setOnClickListener(v->{getSharedPreferences(PREFS,MODE_PRIVATE).edit().remove(HISTORY_KEY).apply();result.setText("Historia tyhjennetty.");});root.addView(clear);status=t("Valmis",14,Color.rgb(119,205,255));root.addView(status);result=t("",13,Color.WHITE);result.setMovementMethod(new ScrollingMovementMethod());root.addView(result);setContentView(sc);}
 private void choose(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,PICK);}
 @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req!=PICK||res!=RESULT_OK||data==null)return;ArrayList<Uri>u=new ArrayList<>();ClipData c=data.getClipData();if(c!=null)for(int i=0;i<c.getItemCount();i++)u.add(c.getItemAt(i).getUri());else if(data.getData()!=null)u.add(data.getData());process(u);}
 private void process(List<Uri>u){merged.setLength(0);status.setText("Luetaan "+u.size()+" kuvaa…");next(u,0);} private void next(List<Uri>u,int i){if(i>=u.size()){analyze(u.size());return;}try{InputImage im=InputImage.fromFilePath(this,u.get(i));recognizer.process(im).addOnSuccessListener(r->{merged.append("\n--- IMAGE ").append(i+1).append(" ---\n").append(r.getText());next(u,i+1);}).addOnFailureListener(e->next(u,i+1));}catch(Exception e){next(u,i+1);}}
 private void analyze(int images){String raw=merged.toString(),low=raw.toLowerCase(Locale.ROOT);long inf=count(low,"infantry"),lan=count(low,"lancer"),mark=count(low,"marksman"),troops=countAny(low,"troops","troop"),loss=countAny(low,"losses","loss"),inj=countAny(low,"injured","wounded"),light=countAny(low,"lightly injured","lightly wounded"),surv=countAny(low,"survivors","survived");double atk=pct(low,"attack"),def=pct(low,"defense"),leth=pct(low,"lethality"),hp=pctAny(low,"health","hp");String outcome=outcome(low),role=role(low),heroes=heroes(low),skills=skills(low);long check=loss+inj+light+surv;double conf=confidence(troops,check,inf+lan+mark,outcome,images,heroes);Record r=new Record(System.currentTimeMillis(),outcome,role,inf,lan,mark,troops,loss,inj,light,surv,atk,def,leth,hp,images,conf,heroes,skills);StringBuilder o=new StringBuilder("BATTLE REPORT 7.1\n");o.append("Outcome: ").append(outcome).append(" • Role: ").append(role).append(" • Confidence: ").append(f(conf)).append("%\nFormation I/L/M: ").append(ratio(inf,lan,mark)).append("\n\nTroops ").append(troops).append(" | Losses ").append(loss).append(" | Injured ").append(inj).append(" | Light ").append(light).append(" | Survivors ").append(surv).append("\n");if(troops>0&&check>0)o.append("Casualty validation: ").append(check).append('/').append(troops).append(check==troops?" ✓":" ⚠ REVIEW").append("\n");o.append("\nHeroes detected: ").append(heroes.isEmpty()?"none":heroes).append("\nSkill/joiner clues: ").append(skills.isEmpty()?"none":skills).append("\n\nStats A/D/L/H: ").append(atk).append(" / ").append(def).append(" / ").append(leth).append(" / ").append(hp).append("\n\nObserved report data only; hero skills are tracked separately from displayed report stats.\n\nRAW OCR\n").append(raw.length()>6000?raw.substring(0,6000)+"…":raw);result.setText(o.toString());status.setText(conf>=70?"Valmis ✓":"Valmis — tarkista OCR ⚠");SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);append(p,r);}
 private String heroes(String s){String[][]h={{"jeronimo","Jeronimo [G1]"},{"flint","Flint [G2]"},{"mia","Mia [G3]"},{"reina","Reina [G4]"},{"hector","Hector [G5]"},{"renee","Renee [G6]"},{"bradley","Bradley [G7]"},{"gatot","Gatot [G8]"},{"hendrik","Hendrik [G8]"},{"xura","Xura [G9]"},{"gregory","Gregory [G10]"},{"freya","Freya [G10]"},{"blanchette","Blanchette [G10]"},{"eleonora","Eleonora [G11]"},{"lloyd","Lloyd [G11]"},{"rufus","Rufus [G11]"},{"norah","Norah [G5]"},{"jessie","Jessie [Epic]"},{"jasser","Jasser [Epic]"},{"seo-yoon","Seo-yoon [Epic]"},{"patrick","Patrick [Epic]"},{"sergey","Sergey [Epic]"}};StringBuilder b=new StringBuilder();for(String[]x:h)if(s.contains(x[0])){if(b.length()>0)b.append(", ");b.append(x[1]);}return b.toString();}
 private String skills(String s){String[]k={"battle manifesto","pyromaniac","bad luck streak","assassin's instinct","stand of arms","tactical genius","rallying beat","super nutrients","defender's edge","worm's ravage","nightmare trace","scorching sun","inferno regiment"};StringBuilder b=new StringBuilder();for(String x:k)if(s.contains(x)){if(b.length()>0)b.append(", ");b.append(x);}return b.toString();}
 private double confidence(long t,long c,long typed,String o,int imgs,String heroes){double x=20;if(imgs>1)x+=10;if(!"UNKNOWN".equals(o))x+=15;if(typed>0)x+=15;if(t>0)x+=15;if(!heroes.isEmpty())x+=5;if(t>0&&c>0)x+=Math.max(0,20-Math.abs(t-c)*100.0/t);return Math.min(100,x);} private void append(SharedPreferences p,Record r){String old=p.getString(HISTORY_KEY,"");String z=r.enc()+(old.isEmpty()?"":"\n"+old);String[]a=z.split("\\n");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(200,a.length);i++){if(i>0)b.append('\n');b.append(a[i]);}p.edit().putString(HISTORY_KEY,b.toString()).apply();}
 private void showHistory(){String h=getSharedPreferences(PREFS,MODE_PRIVATE).getString(HISTORY_KEY,"");if(h.isEmpty()){result.setText("Ei battle dataa.");return;}int n=0,w=0;StringBuilder b=new StringBuilder("BATTLE HISTORY\n\n");for(String row:h.split("\\n")){Record r=Record.dec(row);if(r==null)continue;n++;if("VICTORY".equals(r.outcome))w++;b.append(new SimpleDateFormat("dd.MM HH:mm",Locale.getDefault()).format(new Date(r.time))).append(" • ").append(r.outcome).append(" • ").append(ratio(r.inf,r.lan,r.mark)).append(" • ").append(r.heroes).append("\n");}b.append("\nReports: ").append(n).append(" • OCR victories: ").append(w);result.setText(b.toString());}
 private void exportCsv(){String h=getSharedPreferences(PREFS,MODE_PRIVATE).getString(HISTORY_KEY,"");if(h.isEmpty()){result.setText("Ei exportoitavaa dataa.");return;}StringBuilder c=new StringBuilder("timestamp,outcome,role,infantry,lancer,marksman,ratio,troops,losses,injured,lightly_injured,survivors,attack,defense,lethality,health,images,confidence,heroes,skill_clues\n");for(String row:h.split("\\n")){Record r=Record.dec(row);if(r!=null)c.append(r.csv()).append('\n');}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/csv");i.putExtra(Intent.EXTRA_SUBJECT,"WOS Battle Data 7.1");i.putExtra(Intent.EXTRA_TEXT,"\uFEFF"+c);startActivity(Intent.createChooser(i,"Vie battle data"));}
 private String outcome(String s){return s.contains("victory")||s.contains("won")?"VICTORY":s.contains("defeat")||s.contains("lost")?"DEFEAT":"UNKNOWN";}private String role(String s){return s.contains("attacker")||s.contains("rally leader")?"ATTACK":s.contains("defender")||s.contains("garrison")?"DEFENSE":"UNKNOWN";}private long countAny(String s,String...k){for(String x:k){long v=count(s,x);if(v>0)return v;}return 0;}private long count(String s,String k){Matcher m=Pattern.compile(Pattern.quote(k)+"[^0-9]{0,30}([0-9][0-9, .]{1,})").matcher(s);if(m.find())try{return Long.parseLong(m.group(1).replaceAll("[^0-9]",""));}catch(Exception e){}return 0;}private double pctAny(String s,String...k){for(String x:k){double v=pct(s,x);if(v>0)return v;}return 0;}private double pct(String s,String k){Matcher m=Pattern.compile(Pattern.quote(k)+"[^0-9]{0,20}([0-9]+(?:[.,][0-9]+)?)\\s*%").matcher(s);if(m.find())try{return Double.parseDouble(m.group(1).replace(',','.'));}catch(Exception e){}return 0;}private String ratio(long a,long b,long c){long s=a+b+c;return s==0?"unavailable":f(100.0*a/s)+"/"+f(100.0*b/s)+"/"+f(100.0*c/s);}private String f(double x){return String.format(Locale.US,"%.1f",x);}private TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,8,0,12);return v;}@Override protected void onDestroy(){super.onDestroy();recognizer.close();}
 private static String q(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}private static final class Record{long time,inf,lan,mark,troops,losses,injured,light,surv;double atk,def,leth,hp,conf;String outcome,role,heroes,skills;int images;Record(long t,String o,String r,long i,long l,long m,long tr,long lo,long in,long li,long su,double a,double d,double le,double h,int im,double c,String he,String sk){time=t;outcome=o;role=r;inf=i;lan=l;mark=m;troops=tr;losses=lo;injured=in;light=li;surv=su;atk=a;def=d;leth=le;hp=h;images=im;conf=c;heroes=he;skills=sk;}String enc(){return time+"|"+outcome+"|"+role+"|"+inf+"|"+lan+"|"+mark+"|"+troops+"|"+losses+"|"+injured+"|"+light+"|"+surv+"|"+atk+"|"+def+"|"+leth+"|"+hp+"|"+images+"|"+conf+"|"+heroes.replace("|","/")+"|"+skills.replace("|","/");}String csv(){long s=inf+lan+mark;String ratio=s==0?"":String.format(Locale.US,"%.1f/%.1f/%.1f",100.0*inf/s,100.0*lan/s,100.0*mark/s);return time+","+outcome+","+role+","+inf+","+lan+","+mark+","+q(ratio)+","+troops+","+losses+","+injured+","+light+","+surv+","+atk+","+def+","+leth+","+hp+","+images+","+conf+","+q(heroes)+","+q(skills);}static Record dec(String s){try{String[]x=s.split("\\|",-1);return new Record(Long.parseLong(x[0]),x[1],x[2],Long.parseLong(x[3]),Long.parseLong(x[4]),Long.parseLong(x[5]),Long.parseLong(x[6]),Long.parseLong(x[7]),Long.parseLong(x[8]),Long.parseLong(x[9]),Long.parseLong(x[10]),Double.parseDouble(x[11]),Double.parseDouble(x[12]),Double.parseDouble(x[13]),Double.parseDouble(x[14]),Integer.parseInt(x[15]),Double.parseDouble(x[16]),x.length>17?x[17]:"",x.length>18?x[18]:"");}catch(Exception e){return null;}}}
}