package com.hand33h.tulostaulu;

import android.app.Activity;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class MyAccountActivity extends Activity {
 private static final String PREFS="wos_tulostaulu", API="https://woscontrol.com/api/v1";
 private boolean en; private EditText fid,key,construction,research,training; private TextView profile,status;
 @Override protected void onCreate(Bundle b){super.onCreate(b);SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);en="en".equals(p.getString("lang","fi"));ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(20),dp(18),dp(40));root.setBackgroundColor(Color.rgb(7,23,39));sc.addView(root);
  root.addView(txt("👤  "+tr("OMA TILI","MY ACCOUNT"),26,true,Color.WHITE));root.addView(txt(tr("Yhdistä WOS-profiili FID:llä. Salasanaa ei tallenneta Bunny Kingiin.","Connect your WOS profile by FID. Bunny King never stores your game password."),13,false,Color.rgb(202,224,238)),mp(0,5,0,18));
  fid=input("FID",p.getString("account_fid",""),true);key=input("WOS Control API key",p.getString("api_key",""),false);root.addView(fid);root.addView(key,mp(0,8,0,8));Button connect=button(tr("YHDISTÄ / PÄIVITÄ PROFIILI","CONNECT / REFRESH PROFILE"));root.addView(connect);profile=txt(tr("Ei yhdistettyä profiilia.","No connected profile."),14,false,Color.WHITE);root.addView(profile,mp(0,12,0,18));
  root.addView(txt(tr("PÄIVITYSNOPEUDET","SPEED BONUSES"),14,true,Color.rgb(119,205,255)));root.addView(txt(tr("Jos API ei palauta nopeuksia, syötä pelissä näkyvä kokonaisprosentti. Arvot tallennetaan puhelimeen ja laskurit voivat käyttää niitä.","If the API does not return speed bonuses, enter the total percentage shown in game. Values are saved locally for calculators."),12,false,Color.rgb(202,224,238)),mp(0,4,0,10));
  construction=input(tr("Construction Speed %","Construction Speed %"),p.getString("construction_speed",""),true);research=input("Research Speed %",p.getString("research_speed",""),true);training=input("Training Speed %",p.getString("training_speed",""),true);root.addView(construction);root.addView(research,mp(0,8,0,0));root.addView(training,mp(0,8,0,8));Button save=button(tr("TALLENNA NOPEUDET","SAVE SPEEDS"));root.addView(save);status=txt("",13,true,Color.rgb(119,205,255));root.addView(status,mp(0,10,0,0));
  connect.setOnClickListener(v->connect());save.setOnClickListener(v->{p.edit().putString("construction_speed",construction.getText().toString()).putString("research_speed",research.getText().toString()).putString("training_speed",training.getText().toString()).apply();status.setText(tr("✓ Nopeudet tallennettu","✓ Speeds saved"));});setContentView(sc);
 }
 private void connect(){String f=fid.getText().toString().trim(),k=key.getText().toString().trim();if(f.isEmpty()||k.isEmpty()){toast(tr("Anna FID ja API-avain.","Enter FID and API key."));return;}status.setText(tr("Haetaan profiilia…","Loading profile…"));new Thread(()->{Resp r=get("/player/"+UriEncoder.enc(f),k);if(r.code<200||r.code>=300){ui(()->status.setText("HTTP "+r.code));return;}try{JSONObject j=new JSONObject(r.body);JSONObject p=findPlayer(j);String name=str(p,"nickname","name","player_name","username"),state=str(p,"state_id","state","server","server_id","kingdom"),power=str(p,"might","power","total_power","player_power");Double cs=findPercent(j,"construction_speed","constructionSpeed","build_speed","building_speed");Double rs=findPercent(j,"research_speed","researchSpeed");Double ts=findPercent(j,"training_speed","trainingSpeed","troop_training_speed");getSharedPreferences(PREFS,MODE_PRIVATE).edit().putString("account_fid",f).putString("api_key",k).apply();ui(()->{profile.setText((name.isEmpty()?"FID "+f:name)+(state.isEmpty()?"":"\nState #"+state)+(power.isEmpty()?"":"\nPower: "+power));if(cs!=null)construction.setText(clean(cs));if(rs!=null)research.setText(clean(rs));if(ts!=null)training.setText(clean(ts));status.setText((cs!=null||rs!=null||ts!=null)?tr("✓ Profiili ja saatavilla olevat nopeudet päivitetty","✓ Profile and available speeds refreshed"):tr("✓ Profiili yhdistetty. API ei palauttanut nopeusprosentteja — syötä ne alle kerran käsin.","✓ Profile connected. API did not return speed percentages — enter them once below."));});}catch(Exception e){ui(()->status.setText(tr("Profiilivastausta ei voitu lukea.","Could not read profile response.")));}}).start();}
 private JSONObject findPlayer(JSONObject j){for(String k:new String[]{"player","data","profile","result"})if(j.opt(k) instanceof JSONObject)return (JSONObject)j.opt(k);return j;}
 private Double findPercent(Object n,String...keys){if(n instanceof JSONObject){JSONObject j=(JSONObject)n;for(String k:keys)if(j.has(k)){Double d=asDouble(j.opt(k));if(d!=null)return d;}Iterator<String> it=j.keys();while(it.hasNext()){Double d=findPercent(j.opt(it.next()),keys);if(d!=null)return d;}}else if(n instanceof JSONArray){JSONArray a=(JSONArray)n;for(int i=0;i<a.length();i++){Double d=findPercent(a.opt(i),keys);if(d!=null)return d;}}return null;}
 private Double asDouble(Object v){try{if(v instanceof Number)return ((Number)v).doubleValue();String s=String.valueOf(v).replace("%","").trim();return s.isEmpty()?null:Double.parseDouble(s);}catch(Exception e){return null;}}
 private String clean(double d){return d==(long)d?String.valueOf((long)d):String.valueOf(d);}
 private String str(JSONObject o,String...ks){for(String k:ks){Object v=o.opt(k);if(v!=null&&v!=JSONObject.NULL&&!String.valueOf(v).trim().isEmpty())return String.valueOf(v).trim();}return "";}
 private Resp get(String path,String key){HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(API+path).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(25000);c.setRequestProperty("X-API-Key",key);c.setRequestProperty("Authorization","Bearer "+key);int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();BufferedReader br=new BufferedReader(new InputStreamReader(is,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=br.readLine())!=null)b.append(x);br.close();return new Resp(code,b.toString());}catch(Exception e){return new Resp(-1,e.getMessage());}finally{if(c!=null)c.disconnect();}}
 private EditText input(String h,String val,boolean num){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.rgb(190,207,219));e.setText(val);e.setTextColor(Color.WHITE);e.setSingleLine();e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setInputType(num?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL:InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(25,58,78));g.setStroke(dp(1),Color.rgb(82,155,196));g.setCornerRadius(dp(12));e.setBackground(g);return e;}
 private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT_BOLD);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(20,126,196));g.setCornerRadius(dp(14));b.setBackground(g);return b;}private TextView txt(String s,int z,boolean bold,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}private String tr(String fi,String ee){return en?ee:fi;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private void ui(Runnable r){runOnUiThread(r);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private LinearLayout.LayoutParams mp(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}static class Resp{int code;String body;Resp(int c,String b){code=c;body=b==null?"":b;}}static class UriEncoder{static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return s;}}}
}