package com.hand33h.tulostaulu;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.widget.*;
import java.text.NumberFormat;
import java.util.*;

public class NativeCalculatorActivity extends Activity {
 private static final String PREFS="wos_tulostaulu"; private boolean en; private String mode; private LinearLayout root; private TextView result;
 private final List<Row> rows=new ArrayList<>(); private EditText current,target;
 // Verified public WOS data: per-charm completed-level step costs, levels 1..16.
 private static final long[] CH_GUIDE={0,5,40,60,80,100,120,140,200,300,420,560,580,580,600,600,650};
 private static final long[] CH_DESIGN={0,5,15,40,100,200,300,400,400,400,420,420,450,450,500,500,550};
 private static final long[] CH_SECRET={0,0,0,0,0,0,0,0,0,0,0,0,15,30,45,70,100};
 private static final long[] CH_POWER={0,205700,288000,370000,452000,576000,700000,824000,948000,1072000,1196000,1320000,1444000,1568000,1692000,1816000,1940000};
 // Hero widget step costs 0->1 ... 9->10.
 private static final long[] WIDGET={5,10,15,20,25,30,35,40,45,50};
 @Override protected void onCreate(Bundle b){super.onCreate(b);en="en".equals(getSharedPreferences(PREFS,MODE_PRIVATE).getString("lang","fi"));mode=getIntent().getStringExtra("mode");if(mode==null)mode="chief_gear";
  ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(20),dp(18),dp(40));root.setBackgroundColor(Color.rgb(7,23,39));sc.addView(root);
  LinearLayout hero=box(13,48,76,22);hero.setPadding(dp(20),dp(20),dp(20),dp(20));hero.addView(txt(icon()+"  "+title(),25,true,Color.WHITE));hero.addView(txt(tr("Bunny King • natiivi WOS-laskuri","Bunny King • native WOS calculator"),12,false,Color.rgb(202,224,238)));root.addView(hero,mp(0,0,0,16));
  if(mode.equals("charms"))buildCharms(); else if(mode.equals("hero_gear"))buildHero(); else if(mode.equals("war_academy"))buildWar(); else buildGeneric(); setContentView(sc);
 }
 private void buildCharms(){root.addView(info(tr("Tarkka tasodata 1–16. Laskenta toimii yhdelle charmille tai kaikille 18 charmille.","Exact level data 1–16. Calculate one charm or all 18 charms.")));
  Spinner c=spin(levels(0,16)),t=spin(levels(0,16));root.addView(txt(tr("Nykyinen taso","Current level"),12,true,cyan()));root.addView(c);root.addView(txt(tr("Tavoitetaso","Target level"),12,true,cyan()),mp(0,8,0,0));root.addView(t);
  CheckBox all=new CheckBox(this);all.setText(tr("Laske kaikki 18 charmia","Calculate all 18 charms"));all.setTextColor(Color.WHITE);root.addView(all);
  EditText og=input(tr("Omistat: Charm Guides","Owned: Charm Guides"),true),od=input(tr("Omistat: Charm Designs","Owned: Charm Designs"),true),os=input(tr("Omistat: Charm Secrets","Owned: Charm Secrets"),true);root.addView(og);root.addView(od);root.addView(os);
  result=out();Button b=button(tr("LASKE","CALCULATE"));root.addView(b);root.addView(result,mp(0,12,0,0));b.setOnClickListener(v->{int a=c.getSelectedItemPosition(),z=t.getSelectedItemPosition();if(z<=a){toast(tr("Tavoitteen pitää olla nykyistä tasoa korkeampi.","Target must be above current level."));return;}long g=0,d=0,s=0;for(int i=a+1;i<=z;i++){g+=CH_GUIDE[i];d+=CH_DESIGN[i];s+=CH_SECRET[i];}int n=all.isChecked()?18:1;g*=n;d*=n;s*=n;long pg=Math.max(0,g-val(og)),pd=Math.max(0,d-val(od)),ps=Math.max(0,s-val(os));long power=(CH_POWER[z]-CH_POWER[a])*n;result.setText(tr("TARVE","REQUIRED")+"\nCharm Guides: "+fmt(g)+"  •  "+tr("puuttuu ","missing ")+fmt(pg)+"\nCharm Designs: "+fmt(d)+"  •  "+tr("puuttuu ","missing ")+fmt(pd)+"\nCharm Secrets: "+fmt(s)+"  •  "+tr("puuttuu ","missing ")+fmt(ps)+"\n\nPower: +"+fmt(power));});
 }
 private void buildHero(){root.addView(info(tr("Hero Gearissa on kolme erillistä kehityslinjaa. Tässä tarkka Widget 0–10 -laskuri sekä materiaalivarasto Mastery/Enhance-suunnitteluun.","Hero Gear has three independent tracks. This includes the exact Widget 0–10 calculator plus inventory planning for Mastery/Enhance.")));
  Spinner c=spin(levels(0,10)),t=spin(levels(0,10));root.addView(txt("Widget • "+tr("nykyinen","current"),12,true,cyan()));root.addView(c);root.addView(txt("Widget • "+tr("tavoite","target"),12,true,cyan()));root.addView(t);EditText owned=input(tr("Omistat Widgettejä","Widgets owned"),true);root.addView(owned);result=out();Button b=button(tr("LASKE WIDGETIT","CALCULATE WIDGETS"));root.addView(b);root.addView(result,mp(0,12,0,0));b.setOnClickListener(v->{int a=c.getSelectedItemPosition(),z=t.getSelectedItemPosition();long need=0;for(int i=a;i<z;i++)need+=WIDGET[i];result.setText("Widgets: "+fmt(need)+"\n"+tr("Puuttuu: ","Missing: ")+fmt(Math.max(0,need-val(owned)))+"\n\n"+tr("Mastery Forging käyttää Essence Stones -materiaalia; tasot 11–20 tarvitsevat lisäksi Mythic gearia. Enhance käyttää gear-XP:tä; Mithril-portit ovat Enhance 20/40/60/80/100 ja ascended-vaiheissa.","Mastery Forging uses Essence Stones; levels 11–20 additionally need Mythic gear. Enhance uses gear XP; Mithril gates occur at Enhance 20/40/60/80/100 and ascended stages."));});
 }
 private void buildWar(){root.addView(info(tr("War Academy käyttää Fire Crystal Shardeja. Julkisen datan mukaan vaihto: 5 000 Steel = 1 Shard (enintään 20/pv) ja 10 Fire Crystalia = 13 Shardia (enintään 200 shard-vaihtoa/pv).","War Academy uses Fire Crystal Shards. Public data lists: 5,000 Steel = 1 Shard (max 20/day) and 10 Fire Crystals = 13 Shards (max 200 shard exchanges/day).")));
  EditText steel=input("Steel",true),fc=input("Fire Crystals",true),owned=input(tr("Omistat Fire Crystal Shardeja","Fire Crystal Shards owned"),true),need=input(tr("Tarvittavat Shardit","Shards required"),true);root.addView(steel);root.addView(fc);root.addView(owned);root.addView(need);result=out();Button b=button(tr("LASKE SHARDIT","CALCULATE SHARDS"));root.addView(b);root.addView(result,mp(0,12,0,0));b.setOnClickListener(v->{long fromSteel=Math.min(20,val(steel)/5000),fromFc=Math.min(200,(val(fc)/10)*13),total=val(owned)+fromSteel+fromFc;result.setText(tr("Steel-vaihdosta: ","From Steel: ")+fmt(fromSteel)+"\n"+tr("Fire Crystal -vaihdosta: ","From Fire Crystals: ")+fmt(fromFc)+"\n"+tr("Shardit yhteensä: ","Total Shards: ")+fmt(total)+"\n"+tr("Puuttuu tavoitteesta: ","Missing from target: ")+fmt(Math.max(0,val(need)-total)));});
 }
 private void buildGeneric(){root.addView(info(tr("Tälle osa-alueelle säilytetään materiaalivarasto- ja puutelaskenta. Tasotaulukkoa ei arvata: se lisätään vain vahvistetusta WOS-datasta.","This section keeps inventory/shortage planning. Level tables are not guessed; they are added only from verified WOS data.")));current=input(tr("Nykyinen taso / vaihe","Current level / stage"),false);target=input(tr("Tavoitetaso / vaihe","Target level / stage"),false);root.addView(current);root.addView(target);for(String m:materials())addMat(m);result=out();Button b=button(tr("LASKE PUUTTUVAT","CALCULATE SHORTAGES"));root.addView(b);root.addView(result,mp(0,12,0,0));b.setOnClickListener(v->{StringBuilder s=new StringBuilder();for(Row r:rows){long n=val(r.need),h=val(r.have);s.append(r.name).append(": ").append(fmt(n)).append(" • ").append(tr("puuttuu ","missing ")).append(fmt(Math.max(0,n-h))).append('\n');}result.setText(s.toString());});}
 private void addMat(String n){root.addView(txt(n,14,true,Color.WHITE));LinearLayout l=new LinearLayout(this);EditText a=input(tr("Tarve","Need"),true),b=input(tr("Omistat","Owned"),true);l.addView(a,new LinearLayout.LayoutParams(0,dp(50),1));l.addView(b,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(l);rows.add(new Row(n,a,b));}
 private String[] materials(){switch(mode){case"chief_gear":return new String[]{"Hardened Alloy","Polishing Solution","Design Plans","Lunar Amber"};case"fire_crystals":return new String[]{"Fire Crystals","Refined Fire Crystals","Steel","Speedups (min)"};case"buildings":return new String[]{"Meat","Wood","Coal","Iron","Fire Crystals","Speedups (min)"};case"research":return new String[]{"Meat","Wood","Coal","Iron","Steel","Research Speedups (min)"};case"pets":return new String[]{"Pet Food","Taming Manuals","Energizing Potions","Strengthening Serums","Common Wild Marks","Advanced Wild Marks"};case"troops":return new String[]{"Meat","Wood","Coal","Iron","Training Speedups (min)","Troop count"};case"experts":return new String[]{"Expert XP","Expert Manuals","Expert materials"};case"svs":return new String[]{"Chief Gear materials","Charm materials","Fire Crystals","Hero Gear materials","Pet materials","Speedups (min)","Expected SvS points"};case"bear":return new String[]{"Infantry","Lancers","Marksmen","March capacity","Rally capacity"};case"koi":return new String[]{"Speedups (min)","Fire Crystals","Chief Gear materials","Charm materials","Expected points"};case"chests":return new String[]{"Chest count","Expected primary material","Expected secondary material"};default:return new String[]{"Resource A","Resource B","Resource C"};}}
 private String title(){switch(mode){case"chief_gear":return"Chief Gear";case"charms":return"Chief Charms";case"fire_crystals":return"Fire Crystals";case"buildings":return"Buildings / Furnace";case"research":return"Research";case"war_academy":return"War Academy";case"hero_gear":return"Hero Gear";case"pets":return"Pets";case"troops":return"Troops";case"experts":return"Experts";case"svs":return"SvS Prep";case"bear":return"Bear Trap / Rally";case"koi":return"KOI";case"chests":return"Chests";default:return"WOS Calculator";}}
 private String icon(){switch(mode){case"chief_gear":return"🛡️";case"charms":return"💠";case"fire_crystals":return"🔥";case"buildings":return"🏗️";case"research":return"🧠";case"war_academy":return"🎓";case"hero_gear":return"🦸";case"pets":return"🐾";case"troops":return"⚔️";case"experts":return"👨‍🔬";case"svs":return"⚔️";case"bear":return"🐻";case"koi":return"🧊";case"chests":return"📦";default:return"🧮";}}
 private String[] levels(int a,int b){String[] x=new String[b-a+1];for(int i=a;i<=b;i++)x[i-a]=tr("Taso ","Level ")+i;return x;}private Spinner spin(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}private TextView info(String s){TextView v=txt(s,13,false,Color.rgb(210,228,238));v.setPadding(dp(12),dp(12),dp(12),dp(12));return v;}private TextView out(){return txt(tr("Valmis laskentaan.","Ready to calculate."),14,false,Color.WHITE);}private int cyan(){return Color.rgb(119,205,255);}private String tr(String f,String e){return en?e:f;}private long val(EditText e){try{String s=e.getText().toString().replaceAll("[^0-9]","");return s.isEmpty()?0:Long.parseLong(s);}catch(Exception x){return 0;}}private String fmt(long n){return NumberFormat.getIntegerInstance(Locale.US).format(n);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 private EditText input(String h,boolean num){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.rgb(135,158,174));e.setTextColor(Color.WHITE);e.setSingleLine();e.setPadding(dp(12),dp(10),dp(12),dp(10));e.setInputType(num?InputType.TYPE_CLASS_NUMBER:InputType.TYPE_CLASS_TEXT);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(9,29,44));g.setCornerRadius(dp(11));e.setBackground(g);return e;}private LinearLayout box(int r,int g,int b,int rad){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(r,g,b));d.setCornerRadius(dp(rad));l.setBackground(d);return l;}private TextView txt(String s,int z,boolean bold,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT_BOLD);return b;}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private LinearLayout.LayoutParams mp(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}static class Row{String name;EditText need,have;Row(String n,EditText a,EditText b){name=n;need=a;have=b;}}
}
